language: python
sudo: false

python:
  - "3.3"
  - "3.4"
  - "3.5"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install psycopg2
  - pip install sqlalchemy
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install coveralls
  - pip install WebTest
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests erpblok/tests -v -s --with-coverage --cover-package=erpblok
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - nosetests erpblok/bloks --with-anyblok-bloks -v -s --with-coverage --cover-package=erpblok
  
after_success:
  coveralls
